CREATE TABLE "statuses" (
	"statusId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"alias" varchar(64) NOT NULL,
	CONSTRAINT "statuses_pkey" PRIMARY KEY("statusId"),
	CONSTRAINT "statuses_alias_key" UNIQUE("alias")
);

CREATE TABLE "users" (
	"userId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login" varchar(64) NOT NULL,
	"password" varchar(64) NOT NULL,
	"authKey" varchar(32),
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"lastActivityAt" timestamptz,
	"statusId" integer NOT NULL,
	CONSTRAINT "users_pkey" PRIMARY KEY("userId")
);

CREATE TABLE "vfsFiles" (
	"fileId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"folderId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"path" varchar(255) NOT NULL,
	"params" text,
	"isFavorite" boolean DEFAULT false,
	"mimeType" varchar(255) NOT NULL,
	"fileSize" integer DEFAULT 0,
	"fileExists" boolean NOT NULL DEFAULT true,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "vfsFiles_pkey" PRIMARY KEY("fileId")
);

CREATE TABLE "vfsFolders" (
	"folderId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"parentFolderId" integer,
	"title" varchar(255) NOT NULL,
	"isFavorite" boolean DEFAULT false,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "vfsFolders_pkey" PRIMARY KEY("folderId")
);

CREATE TABLE "vfsHashes" (
	"hash" varchar(40) NOT NULL,
	"namespace" varchar(32) NOT NULL,
	"extension" varchar(4) NOT NULL,
	"fileSize" integer NOT NULL DEFAULT 0,
	"width" integer NOT NULL DEFAULT 0,
	"height" integer NOT NULL DEFAULT 0,
	"blurhash" text,
	"error" text,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"indexedAt" timestamptz,
	CONSTRAINT "vfsHashes_pkey" PRIMARY KEY("hash", "namespace")
);

CREATE INDEX "IX_FK_users_statusId_users" ON "users" (
	"statusId"
);

CREATE INDEX "IX_FK_vfsFiles_folderId_vfsFiles" ON "vfsFiles" (
	"folderId"
);

CREATE INDEX "IX_FK_vfsFiles_statusId_vfsFiles" ON "vfsFiles" (
	"statusId"
);

CREATE INDEX "IX_FK_vfsFolders_folderId_vfsFolders" ON "vfsFolders" (
	"parentFolderId"
);

CREATE INDEX "IX_FK_vfsFolders_statusId_vfsFolders" ON "vfsFolders" (
	"statusId"
);

CREATE INDEX "IX_vfsHashes_indexedAt" ON "vfsHashes" (
	"indexedAt"
);

ALTER TABLE "users" ADD CONSTRAINT "FK_users_statusId" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_folderId_fkey" FOREIGN KEY ("folderId")
	REFERENCES "vfsFolders"("folderId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "vfsFiles_statusId_fkey" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_parentFolderId_fkey" FOREIGN KEY ("parentFolderId")
	REFERENCES "vfsFolders"("folderId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "vfsFolders_statusId_fkey" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

